handlebars:
  locale: en_EN
  resourceBaseNames: https://raw.githubusercontent.com/ali-v-1985/handlebars-i18n/master/externalized_resources/labels, classpath:labels
  template: classpath:example.hbs


logging:
  level:
    root: ERROR
    me.valizadeh: DEBUG
  pattern:
    console: "%msg%n"